### ISSUE TITLE
请问有没有可能增加阿里云的语音引擎的可能？

### ISSUE THREAD

**Issue by fakedestinyck** [Noisyfox/ACT.FoxTTS#12]
作者大大您好，想问问有没有增加阿里云语音合成引擎的可能？或者说如果您没有时间去多增加一个的话，有没有可能略微提点一下这个应该怎么加 我自己试试加也行（？）辛苦大大

**Comment by Noisyfox** [comment]
理论上可以，我粗略的看了一下，阿里云提供的c# SDK需要很多额外的native dll依赖不太方便打包进插件里，我建议是直接调用阿里云的Restful api而不是用他们的SDK。
理论上只要调用两个API就可以实现了，先调用 https://help.aliyun.com/document_detail/113251.html 获取 Token，然后调用https://help.aliyun.com/document_detail/94737.html 生成音频就好。

**Comment by fakedestinyck** [comment]
感谢回复！原来还有这层考虑！学习了。restful api我也看了 如果能用restful api的话对我这种不会windows编程的确实是好事，只不过就是不太清楚怎么让TTS直接去做网络请求生成T_T

**Comment by fakedestinyck** [comment]
对了还有一个小问题想问问有没有实现的可能：
就是我看阿里云的 `voice` 参数是可以使用自己训练的语音模型的？（好像讯飞也是可以的）就是想问问就是和现在的已经有的下拉框选择发音人不太一样，有没有可能多一个输入类型的让我们用户自己填 `voice` 这个参数的值呢？（这个是不是要改的有点多

**Comment by Noisyfox** [comment]
> 感谢回复！原来还有这层考虑！学习了。restful api我也看了 如果能用restful api的话对我这种不会windows编程的确实是好事，只不过就是不太清楚怎么让TTS直接去做网络请求生成T_T

部分已有引擎就是用的restful api实现的，比如这个
https://github.com/Noisyfox/ACT.FoxTTS/blob/66c85e3d4624c0622e603cf5e523af3cbe31f072/ACT.FoxTTS/ACT.FoxTTS/engine/youdao/YoudaoTTSEngine.cs#L77-L87
这里用的是POST，阿里云的API同时支持GET和POST，不过我觉得如果要实现比如SSML之类的可能用POST会比较方便，而且也没有URL长度限制，所以可以用类似的写法。



> 就是我看阿里云的 `voice` 参数是可以使用自己训练的语音模型的？（好像讯飞也是可以的）就是想问问就是和现在的已经有的下拉框选择发音人不太一样，有没有可能多一个输入类型的让我们用户自己填 `voice` 这个参数的值呢？（这个是不是要改的有点多

可以做，只不过当时考虑应该用的人不会太多所以就没加。理论上加个TextBox让用户自己填就好。只不过类似微软语音
https://github.com/Noisyfox/ACT.FoxTTS/blob/66c85e3d4624c0622e603cf5e523af3cbe31f072/ACT.FoxTTS/ACT.FoxTTS/engine/azure/AzureTTSEngine.cs#L21-L98
（以及这个阿里云语音），它不同的发音人支持的情感之类的不一样，所以如果要完整实现所有功能的自定义的话就要再多加几个情感输入框之类的，虽然难度不大但是就是比较繁琐，所以我就懒得加了。

**Comment by fakedestinyck** [comment]
> 这里用的是POST，阿里云的API同时支持GET和POST，不过我觉得如果要实现比如SSML之类的可能用POST会比较方便，而且也没有URL长度限制，所以可以用类似的写法。

学习了！确实哦文本太长了的话GET就写不下了

> 只不过类似微软语音它不同的发音人支持的情感之类的不一样，所以如果要完确实整实现所有功能的自定义的话就要再多加几个情感输入框之类的，虽然难度不大但是就是比较繁琐，所以我就懒得加了。

这个确实，情感之类的感觉更加不会有人闲到去改这个了

> 可以做，只不过当时考虑应该用的人不会太多所以就没加。理论上加个TextBox让用户自己填就好。

那大大预计会做这个嘛，如果没时间的话我也可以看看能不能研究一下大佬的代码然后搞一个提个这个PR之类的，因为好像我确实也没在网上看到有别人提类似的需求[捂脸]

**Comment by Noisyfox** [comment]
如果只是加个自定义人声，但是不用自定义什么情感啥的那倒是不算麻烦。不过我最近时间不多，只能抽空整一整。

**Comment by Noisyfox** [comment]
初步加了阿里云tts，你可以试一下 https://ci.appveyor.com/api/buildjobs/4ei3kng1ep9ldv50/artifacts/ACT.FoxTTS-3.2.0.172-Release.7z

自定义人声还没加。

**Comment by PaleNutcrackers** [comment]
关于自定义人声
我试着直接敲了一段 new AliyunVoice("pt_appkey_nickname", "nickname"), 其中appkey与nickname 已正确填写完成 发现会返回
Unable to complete the request 41020001/51020001 TTS:TtsClientError:cannot found /home/admin/dynamic/pt_appkey_nickname 阿里云方面工单尚未回复

**Comment by Noisyfox** [comment]
加了阿里云的自定义人声功能：
https://ci.appveyor.com/api/buildjobs/a0hoi3ufxgfnoud7/artifacts/ACT.FoxTTS-3.2.0.178-Release.7z

**Comment by fakedestinyck** [comment]
救命我没看到回复的提示。。

> 初步加了阿里云tts，你可以试一下 https://ci.appveyor.com/api/buildjobs/4ei3kng1ep9ldv50/artifacts/ACT.FoxTTS-3.2.0.172-Release.7z
自定义人声还没加。

大佬你好快……

> 加了阿里云的自定义人声功能：
https://ci.appveyor.com/api/buildjobs/a0hoi3ufxgfnoud7/artifacts/ACT.FoxTTS-3.2.0.178-Release.7z

试过了！可以用！膜拜大佬T-T辛苦了❤️

**Comment by fakedestinyck** [comment]
【我先不close？等你推到正式环境了你来close？】

**Comment by Noisyfox** [comment]
这个先关了好了，其它引擎的自定义语音设置我准备另开issue做，不然这个issue内容太多了2333

**Comment by fakedestinyck** [comment]
> 

好耶 我才看到这个））
要是到时候有别的引擎自定义语音我也可以来帮忙测试！另外我顺腾摸瓜找到了大大的paypal嘿嘿希望没有找错））
