### ISSUE TITLE
[Feature request] 文字的正则替换

### ISSUE THREAD

**Issue by m13253** [Noisyfox/ACT.FoxTTS#2]
十分感谢您创作这个插件程序！

在使用这个插件的时候，我发现百度 TTS 特定音色某些单词的发音不正确（比如「女声」音色会把「AOE」当作一整个单词来念）
目前我通过将音色改为「男声」或者编辑时间轴文件来让其正确发音。
请问是否有能力增加文字正则替换功能，可以批量进行文字替换？

这个功能的重要程度并不高，如果您有闲暇可以考虑一下。

**Comment by Noisyfox** [comment]
2.1.0 增加了这个功能~
