### ISSUE TITLE
新版本1.0.4百度语音引擎无法调用

### ISSUE THREAD

**Issue by ShadyWhite** [Noisyfox/ACT.FoxTTS#3]
不知道是普遍问题还是我个人的问题，我尝试申请了新的百度语音API，插件还是无法正常工作，具体日志如下：
[10:17:38] TTSEngine Changed: fromView = True, engine = ttsEngineBaidu
[10:17:38] yukkuriEnabled = True
[10:17:39] TTSYukkuri injected!
[10:18:07] System.AggregateException: 发生一个或多个错误。 ---> System.Net.Http.HttpRequestException: 发送请求时出错。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   在 ACT.FoxCommon.update.UpdateCheckerBase`2.UpdateCheckerThread.DoWork(UpdateContext context)
---> (内部异常 #0) System.Net.Http.HttpRequestException: 发送请求时出错。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于远程方已关闭传输流，身份验证失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---<---

[10:18:13] Baidu.Aip.AipException: 操作超时
   在 Baidu.Aip.AipServiceBase.SendRequetRaw(AipHttpRequest aipRequest)
   在 Baidu.Aip.Speech.Tts.PostAction(AipHttpRequest aipReq)
   在 Baidu.Aip.Speech.Tts.Synthesis(String text, Dictionary`2 options)
   在 ACT.FoxTTS.engine.baidu.BaiduTTSEngine.Speak(String text, Object playDevice, Boolean isSync, Nullable`1 volume)
   在 CallSite.Target(Closure , CallSite , ITTSEngine , String , Object , Boolean , Nullable`1 )
   在 System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid5[T0,T1,T2,T3,T4](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   在 ACT.FoxTTS.FoxTTSPlugin.Speak(String text, Object playDevice, Boolean isSync, Nullable`1 volume)

**Comment by Noisyfox** [comment]
我这里是好的诶，你这个看起来像是网络有点问题？重启试试看。

**Comment by ShadyWhite** [comment]
> 我这里是好的诶，你这个看起来像是网络有点问题？重启试试看。

谢谢大佬，问题已查明，是我的Clash规则的问题，现已修复。
