### ISSUE TITLE
我用系统的 TTS，超过 27 个字符以上的 TTS 就没声音，27 个以下的没问题。

### ISSUE THREAD

**Issue by kyan001** [Noisyfox/ACT.FoxTTS#5]

**Comment by Noisyfox** [comment]
应该是缓存目录路径太长了。你点一下“打开缓存文件夹”，然后看下文件夹的路径是不是很长。

**Comment by Noisyfox** [comment]
https://ci.appveyor.com/project/Noisyfox/act-foxtts/builds/38543923/job/vbxoivdwhpmjgn7t/artifacts
试一下这个版本看看
