### ISSUE TITLE
系统自带TTS音量过小

### ISSUE THREAD

**Issue by retaker** [Noisyfox/ACT.FoxTTS#9]
如题，我所在的网络如果使用微软语音引擎的话经常会卡顿，所以需要使用系统自带TTS.
但是系统自带TTS的声音比微软语音小了大概30%，打本时经常听不清，请求帮助。
谢谢。

**Comment by Noisyfox** [comment]
https://github.com/Noisyfox/ACT.FoxTTS/releases/tag/3.1.0

现在音量能调大到300%了，试一下够不够

**Comment by retaker** [comment]
@Noisyfox 很抱歉现在才回复，刚过本。
我根据ACT提示下载了最新的3.2.0版本，并没有发现系统TTS音量增强选项。
Edit: 我的，我瞎了，我找到了，在主音量下面
